config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => {:registrations => "users/registrations"}
  root 'resources#index'
  resources :resources, only:[:index,:new, :create, :show, :destroy, :edit, :update] do
    member do
      post :comment
    end
  end
  resources :users, only:[:edit, :update] do
  end

end

app/views/resources/_form.html.erb
<%= image_tag "logo.jpg", style:"width:100%;height:250px;"%>
<nav class="navbar navbar-default">
    <div class="container-fluid">
      <!-- Collect the nav links, forms, and other content for toggling -->
      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1" style="margin-left:25%;">
        <ul class="nav navbar-nav">
          <li class="active"><%= link_to '全部', resources_path%></li>
          <% @classifications.each do |c|%>
          <li id="<%= c.id%>">
          <a href="<%= resources_path(classification: c.id)%>"><%= c.name%></a>
          </li>
          <% end %>
        </ul>
        <form class="navbar-form navbar-left" role="search" style="margin-left: 22%;">
          <div class="form-group">
            <input type="text" class="form-control" placeholder="关键字搜索" name="keyword"  value="<%= params[:keyword]%>" >
          </div>
          <button type="submit" class="btn btn-default">搜索</button>
        </form>

      </div><!-- /.navbar-collapse -->
    </div><!-- /.container-fluid -->
</nav>

app/views/resources/_form_edit.html.erb
<div style="text-align:center">
  <%= simple_form_for @resource do |f|%>
    <div style="margin-top: 5%;">
      <label>标题 : </label>
      <%= f.text_field :title, class:"form-control", style:"margin-right: 11%;", id:"title"%>
      <label>分类 : </label>
       <%= f.select(:classification_id, @classifications.map{|c| [c.name,c.id]}, {} ,{class:"form-control", style:"width: 100px;", value:"#{params[:classification]}"})%>
       <p style="margin-left: -22%;color: #5BC0DE;margin-top: 1%;">提示:标题不能超过27个字符</p>
      <div style="width:36%;margin-left:32%;margin-top: 1%;">
        <%= f.kindeditor :content, :allowFileManager => false%>
      </div>
      <%= f.hidden_field :user_id, value: current_user.id%>
      <%= f.submit '保存',class:"btn btn-info", style:"width:36%;margin-top: 1%;"%>
    </div>
  <% end %>
</div>
<script type="text/javascript">
 $(function(){
  $("#title").keyup(function(){
   var len = $(this).val().length;
   if(len > 26){
    $(this).val($(this).val().substring(0,27));
   }
  });
 });
</script>

app/views/resources/edit.html.erb
<%= render 'form_edit'%>

app/views/resources/index.html.erb
<%= render "form"%>
<div >
  <div>
    <div class="left_content">
      <div style="background-color:#D9EDF7;height:40px;width:100%;">
        <a href="<%= resources_path%>" class="a" style="text-decoration: none;margin-left: 10px;">全部</a>
        <a href="<%= resources_path%>" class="a" style="text-decoration: none;margin-left: 5px;">最新</a>
        <a href="" class="a" style="text-decoration: none;margin-left: 5px;">热门</a>
        <a href="<%= resources_path(tag: 'essence')%>" class="a" style="text-decoration: none;margin-left: 5px;">精华</a>
        <span style="text-decoration: none;margin-left: 203px;">作者/日期</span>
        <span style="text-decoration: none;margin-left: 32px;">回复</span>
        <span style="text-decoration: none;margin-left: 30px;">最后回复</span>
      </div>
      <% @resources.each do |r|%>
      <div style="height:40px;width:100%;border-bottom: 1px solid #eeeeee;" class="col-sm-12">
        <div style="width:58%;height:100%;float:left;margin-left: -12px;">
          <span style="color:#F4A460">[<%= r.classification.name%>]</span>
          <a href="<%= resource_path(r.id)%>" data-no-turbolink = "true"  style="font-size:110%;color:#000;line-height: 2.5;">
            <% if r.title.length>17%>
              <%= r.title[0..17]+'...'%>
            <% else %>
              <%= r.title%>
            <% end %>
          </a>
        </div>
        <div style="width:15%;height:100%;float:left;text-align:center;margin-left: 12px;"><%= r.user.nickname%><p><%= r.created_at.to_time.strftime('%Y-%m-%d')%></p></div>
        <div style="width:12%;height:100%;float:left;text-align:center;padding-top: 8px;"><span class="badge"><%= r.comments.size%></span></div>
        <div style="width:15%;height:100%;float:left;text-align:center;padding-top: 10px;">
          <% if r.comments.last.present?%>
            <%= r.comments.last.user.nickname%>
          <% else %>
            <span>无人回复</span>
          <% end %>
        </div>
      </div>
      <% end %>
      <div style="text-align:center;"><%= paginate @resources %></div>
    </div>
  </div>
  <div style="float: left;">
  <% if user_signed_in?%>
    <div class="right_top">
      <div class="panel panel-info">
        <div class="panel-heading ">分享一下<span class="glyphicon glyphicon-arrow-down"></span></div>
        <div class="panel-body">
          <div class="btn-group">
            <button type="button" class="btn btn-danger"><%= link_to '发布新帖', new_resource_path, 'data-no-turbolink' => true, style:"color: #fff;text-decoration: none;"%></button>
            <button type="button" class="btn btn-danger dropdown-toggle" data-toggle="dropdown" aria-expanded="false">
              <span class="caret"></span>
              <span class="sr-only">Toggle Dropdown</span>
            </button>
            <ul class="dropdown-menu" role="menu">
            <% @classifications.each do |c|%>
              <li><a href="<%=new_resource_path(classification: c.name)%>" data-no-turbolink=true><%= c.name%></a></li>
            <% end %>
            </ul>
          </div>
        </div>
      </div>
    </div>
  <% else %>
  <% end %>
    <div class="right_content" style="background-image: url(/assets/img.jpeg);">
<!--       <p style="text-align:center"><%= image_tag 'notice.png'%></p>
      <p style="text-align:center">占位</p>
      <p style="text-align:center">占位</p>
      <p style="text-align:center"><%= image_tag 'link.png'%></p> -->
    </div>
  </div>
</div>

<!-- <div class="footer"></div>
 --><!-- <script type="text/javascript">
  $(document).ready(function(){
    $("#1").click(function(){
      $("#1").addClass("active")
     });
  });
</script> -->

app/views/resources/new.html.erb
<%= render "form_edit"%>

app/views/resources/show.html.erb
<%= render 'form'%>
<div style="float:left;  margin-left: 18%;">
  <div class="show_left_content">
    <div style="background-color:#F5F5F5;height:85px;width:100%;">
      <strong style="font-size: 150%;padding-left: 2%;line-height: 3;">
        <% if @resource.title.size>30%>
          <%= @resource.title[0..30]+'...'%>
        <% else %>
          <%= @resource.title%>
        <% end %>
      </strong><br>
      <span class="min_title"><%= @resource.classification.name%></span>
      <span class="min_title">
        <% if release_time(@resource.created_at)==0%>
          由<%=@resource.user.nickname%>于24小时内发布
        <% else %>
          由<%=@resource.user.nickname%>于<%= release_time(@resource.created_at)%>天前发布
        <% end %>
      </span>
    </div>
    <div style="padding-top:2%;padding-bottom:2%">
     <%= raw @resource.content%>
    </div>
    <% if current_user==@resource.user%>
    <div style="background-color:#F5F5F5;height:35px;width:100%;">
      <%= link_to '', resource_path(id:@resource.id), method: :delete, class:"glyphicon glyphicon-trash", style:"text-decoration: none;color: #000;float:right;line-height:40px;margin-right:3%", title:"删除本贴"%>
      <%= link_to '', edit_resource_path(id:@resource.id), class:"glyphicon glyphicon-pencil", style:"text-decoration: none;color: #000;float:right;line-height:40px;margin-right:3%", title:"编辑本贴", 'data-no-turbolink' => true%>
    </div>
    <% end %>
  </div>
  <div class="left_comment">
    <div style="background-color:#F0F8FF;height:50px;width:100%;text-align: center;margin-bottom: 10px;">
      <strong style="line-height: 50px;">评论列表</strong>
    </div>
    <% @comment_list.each_with_index  do |c, index|%>
    <div style="height:80px;">
      <div style="float:left;text-align: center;">
        <%if c.user.avatar_url.present?%>
          <%= image_tag(c.user.avatar_url(:large), class:"head")%>
        <% else %>
          <%= image_tag 'head.jpg', class:"head", style:"height:55px;width:55px;"%>
        <% end %>
        <p style="padding-left:11px;font-size:85%;"><%= c.user.nickname%></p>
      </div>
      <div style="padding-top: 13px;">
        <span><%= raw c.content%></span>
      </div>
      <div style="float: right;position: relative;top: 50%;">
        <%= index+1%>楼
      </div>
    </div><hr>
    <% end %>
  </div>
    <div style="text-align:center;margin-left: 50%;"><%= paginate @comment_list %></div>
  <div class="comment">
  <% if current_user.present?%>
    <%= form_for :comment, url:{action: 'comment'} do |f|%>
      <%= f.kindeditor :content, :allowFileManager => false, :simple_mode => true%>
      <span><%= f.submit '评论', style:"margin-top: 5%;margin-bottom: 5%;", class:"btn btn-info"%></span>
      <%= f.hidden_field :user_id, value: current_user.id%>
      <%= f.hidden_field :resource_id, value: params[:id]%>
    <% end %>
  <% end %>
  </div>
</div>
<div style="float: left;margin-left: 8%;">
<% if user_signed_in?%>
  <div class="right_top" >
    <div class="panel panel-info">
      <div class="panel-heading ">分享一下<span class="glyphicon glyphicon-arrow-down"></span></div>
      <div class="panel-body">
        <div class="btn-group">
          <button type="button" class="btn btn-danger"><%= link_to '发布新帖', new_resource_path, 'data-no-turbolink' => true, style:"color: #fff;text-decoration: none;"%></button>
          <button type="button" class="btn btn-danger dropdown-toggle" data-toggle="dropdown" aria-expanded="false">
            <span class="caret"></span>
            <span class="sr-only">Toggle Dropdown</span>
          </button>
          <ul class="dropdown-menu" role="menu">
          <% @classifications.each do |c|%>
            <li><a href="<%=new_resource_path(classification: c.name)%>" data-no-turbolink=true><%= c.name%></a></li>
          <% end %>
          </ul>
        </div>
      </div>
    </div>
  </div>
<% else %>
<% end %>
  <div class="right_content">

  </div>
</div>
</div>